### ISSUE TITLE
Dashboard display issues on MS Edge

### ISSUE THREAD

**Issue by hmgaudecker** [covid-19-impact-lab/utilities#11]
Courtesy of a coauthor. Is this a known thing with bokeh? Or something we could fix? Another thing: Is it useful to add Dominik to the repo?

![image](https://user-images.githubusercontent.com/158456/78987263-d2e21c80-7b2d-11ea-84b5-6c7e232aeca7.png)

**Comment by roecla** [comment]
First of all, thanks for the bug report. 

So, there was a bokeh bug with Microsoft Edge but that was fixed back in 2016.

Is Javascript enabled? With Javascript inactivated bokeh cannot work properly. 
[Here](https://www.windowsdigitals.com/how-to-enable-javascript-in-microsoft-edge-windows-10/) is an instruction on how to enable it on Windows 10.

**Comment by hmgaudecker** [comment]
Cool, thanks for the clarification. Is it possible to check for that from the server side and display something else instead? Just trying to minimise questions in the future...

**Comment by roecla** [comment]
It's just a guess. Could you verify that that was the problem?

It should be possible to have a warning if a user comes to the site with JavaScript disabled (e.g. [here](https://stackoverflow.com/a/8919563)).

**Comment by roecla** [comment]
I checked with another Windows User. There everything rendered correctly with Edge.

Also, I did not read well when I looked up the enabling JavaScript instructions above. There it says in an update "[this] means that JavaScript in Microsoft Edge will now be forced enabled by default."

So this is unlikely to be due to JavaScript. I have not really another hypothesis for the moment so I am going to close this for the moment until we get more similar reports.
